config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'posts#index'
  namespace :admin do
    resources :posts, only: %i[index create new edit update destroy]
    resources :users, only: %i[index create new edit destroy]
  end

  resources :posts, only: %i[index show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  acts_as_punchable
  paginates_per 6

  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :image, ImageUploader
  validates :title, :description, presence: true
  belongs_to :user, counter_cache: true

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  paginates_per 6
  validates :role, presence: true
  has_many :posts, dependent: :destroy
end

app/controllers/admin/posts_controller.rb
# frozen_string_literal: true

module Admin
  class PostsController < ApplicationController
    helper PostsHelper
    before_action :authenticate_user!
    before_action :set_post, only: %i[edit destroy update]

    def index
      @posts = policy_scope(Post).page(params[:page])
    end

    def new
      @post = current_user.posts.new
      authorize @post
    end

    def edit; end

    def create
      @post = current_user.posts.new(post_params)
      authorize @post
      if @post.save
        redirect_to post_path(@post), notice: 'Post was successfully created.'
      else
        render :new
      end
    end

    def update
      if @post.update(post_params)
        redirect_to post_path(@post), notice: 'Post was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @post.destroy
      redirect_to admin_posts_path, notice: 'Post was successfully destroyed.'
    end

    private

    def set_post
      @post = Post.friendly.find(params[:id])
      authorize @post
    end

    def post_params
      params.require(:post).permit(:title, :description, :image)
    end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < ApplicationController
    helper UserHelper
    before_action :authenticate_user!

    def index
      @users = User.all
      authorize @users
    end

    def new
      @user = User.new
      authorize @user
    end

    def create
      @user = User.new(user_params)
      authorize @user
      if @user.save
        redirect_to admin_users_path, notice: 'Copywriter was successfully created.'
      else
        render :new
      end
    end

    def destroy
      @user = User.find(params[:id])
      authorize @user
      @user.destroy
      redirect_to admin_users_path, notice: 'User was successfully deleted.'
    end

    private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show update]

  def index
    @posts = Post.order(:created_at).page(params[:page])
  end

  def show
    @post.punch(request)
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :image)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def author(post:)
    User.find_by(id: post.user_id).email
  end

  def get_random_posts_for_page
    @posts = Post.all.sample(3)
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/admin/posts/_form.html.erb
<%= form_with(model: post, url: admin_posts_path, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control my-2' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control my-2' %>
  </div>
  
  <div class="field">
    <%= form.label :cover %>
    <%= form.file_field :image, class: 'form-control-file  my-2' %>
  </div>

  <div class="actions">
    <%= form.submit "Save post", class: 'btn btn-success my-2' %>
  </div>
<% end %>

app/views/admin/posts/_form_edit.html.erb
<%= form_with(model: @post, url: admin_post_path(@post), local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control my-2' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control my-2' %>
  </div>
  
  <div class="field">
    <%= form.label :cover %>
    <%= form.file_field :image, class: 'form-control-file  my-2' %>
  </div>

  <div class="actions">
    <%= form.submit "Save post", class: 'btn btn-success my-2' %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:blog_active, 'active') %>
<h1>Editing Post</h1>

<%= render 'form_edit', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/index.html.erb
<% provide(:page_title, "All Posts | Admin ") %>
<% provide(:admin_active, 'active') %>
<tr>
<td class='btn btn-sm btn-warning'>Posts</td>
<% if current_user.role == 'admin' %>
<td><%= link_to 'Users', admin_users_path %></td>
<% end %>
</tr>
<div class="row">
  <table class="table table-striped">
  <% @posts.each do |post| %>  
    <tr>
      <td><%= link_to post.title, post %></td>
      <td><%= author(post: post) %></td>
      <td><%= post.created_at %></td>      
      <td><%= link_to 'Edit', edit_admin_post_path(post), class: 'btn btn-sm btn-warning' %></td>
      <% if current_user.role == 'admin' %>
        <td><%= link_to 'Remove', admin_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, 
      class: 'btn btn-sm btn-danger' %></td>
      <% end %>
    </tr>
  <% end %>
  </table>
  <%= paginate @posts %> 
  <div>
    <%= link_to 'New post', new_admin_post_path, class: 'btn btn-read ml-3' %>
  </div>
</div>

app/views/admin/posts/new.html.erb
<% provide(:page_title, 'New Post') %>

<%= render 'form', post: @post %>

app/views/admin/users/index.html.erb
<% provide(:page_title, "All Users | Admin ") %>
<% provide(:admin_active, 'active') %>
<tr>
<td class='btn btn-sm btn-warning'>Users</td>
<td><%= link_to 'Posts', admin_posts_path %></td>
</tr>
<div class="row">
  <table class="table table-striped">
  <% @users.each do |user| %>  
    <tr>
      <td><%= link_to user.email %></td>
      <td><%= user.role %></td>
      <td><%= user.posts_count %> post(s)</td>
      <td><%= user.created_at %></td>
      <td><%= link_to 'Remove', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, 
      class: 'btn btn-sm btn-danger' %></td>
    </tr>
  <% end %>
  </table>
  <div>
    <%= link_to 'New user', new_admin_user_path, class: 'btn btn-read' %>
  </div>
</div>

app/views/admin/users/new.html.erb
<body id="LoginForm">
<div class="container">
  <div class="login-form">
    <div class="main-div">
      <div class="panel">
        <h2>Register copywriter</h2>
        <p>Please enter email and password</p>
        <%= form_for(resource, as: resource_name, url: admin_users_path(resource_name)) do |f| %>
        <%= devise_error_messages! %>
          <div class="form-group">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: 'Email Adress', class: 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.label :password %><br />
            <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
          </div>
            <div class="form-group">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
          </div>
          <div class="actions">
            <%= f.submit 'Register', class: 'btn btn-primary' %>
          </div>
        <% end %>
    </div>
  </div>
</div>
</div>
</body>

app/views/layouts/_navbar.html.erb
<div class="collapse" id="exCollapsingNavbar">
  <div class="collapse-bg p-a-1">
    <div class='card'>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
      </ul>
    </div>
  </div>
</div>
<nav class="navbar navbar-light bg-faded">
  <div class='container'>
    <a class='navbar-brand' href='/'>
      Test<span class='light'>blog</span>
    </a>
    <nav class="navbar navbar-expand-sm">
    <ul class="nav navbar-nav pull-sm-right hidden-xs-down">
      <li class="nav-item">
        <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
      </li>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Admin panel', admin_posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>      
    <% end %>  
    </ul>
  </nav>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% unless notice.nil? %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/notice' %>
    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_image.html.erb
<% if post.image.file.nil? %>
  <div class="card-topper" style='background-image: url(https://images.pexels.com/photos/1709531/pexels-photo-1709531.jpeg);'></div>
<% else %>
  <div class="card-topper" style='background-image: url(<%= post.image_url(:thumb) %>);'></div>
<% end %>	

app/views/posts/_post.html.erb
<div class='col-sm-6 col-lg-4'>
  <div class="card">
    <%= render 'image', post: post %>
    <div class="card-block">
      <h4 class="card-title"><%= link_to post.title, post %></h4>
      <p class="viewed">Viewed <%= post.hits %> times</p>
      <p class="card-text"><%= truncate(post.description, length: 130) %></p>
      <%= link_to 'Read more', post, class: 'btn btn-read' %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% provide(:page_title, "All Posts") %>
<% provide(:blog_active, 'active') %>
 <div class="row">
  <%= render @posts %>
 </div>

 <%= paginate @posts %>

app/views/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_active, 'active') %>

<div class='container'>
	<div class="row pb-3">	
		<div class="col-md-auto col-xs-text-center">
			<div style='font-family: Helvetica Neue'>
			  <h1 class='pb-3'><%= @post.title %></h1>
				<% if @post.image.file.present? %>
			  <%= image_tag @post.image_url, class: "img-fluid img-thumbnail pb-4"%>
				<% end %>
				<div class='container pb-3'>	
	    		<p class='text-left'><%= @post.description %></p>
	    	</div>
	  		<%= link_to 'Back to blog', root_path, class: 'btn btn-read' %>
  		</div>  	
  </div>
</div>
<% get_random_posts_for_page %>
<h1>Similar posts</h1>
<div class="row mt-2">		
	<%= render @posts %>
</div>